ussd_code = input("Enter ussd code")
print("welcome to nigeria")
print("enter,", ussd_code)
num1 = print("1. check balance")
num2 = print("2. buy airtime")
num3 = print("3. buy data")
choice = int(input("pick option: "))
print(f"thank you {num2} is been processed")
airtime_amount = int(input("airtime amount"))
print("Your airtime as been approved")